name: .NET Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build for Windows
        run: dotnet build --configuration Release --no-restore

      - name: Publish for Windows
        run: >
          dotnet publish
          -c Release
          -r win-x64
          --self-contained
          -f net8.0
          -o bin\Release\net8.0\publish\windows
          /p:PublishSingleFile=false
          /p:PublishReadyToRun=true
          /p:PublishAot=true

      - name: Build for MacOS M series
        run: dotnet build --configuration Release --no-restore

      - name: Publish for MacOS M series
        run: >
          dotnet publish
          -c Release
          -r osx-arm64
          --self-contained
          -f net8.0
          -o bin/Release/net8.0/publish/mac
          /p:PublishSingleFile=false
          /p:PublishReadyToRun=true
          /p:PublishAot=true

      - name: Upload Artifact for Windows
        uses: actions/upload-artifact@v3
        with:
          name: application-windows
          path: bin\Release\net8.0\publish\windows\*.exe

      - name: Upload Artifact for MacOS
        uses: actions/upload-artifact@v3
        with:
          name: application-macos
          path: bin/Release/net8.0/publish/mac/*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          tag_name:     ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft:        false
          prerelease:   false

      - name: List files in the publish directory
        run: |
          dir bin\Release\net8.0\publish\windows
          ls bin/Release/net8.0/publish/mac

      - name: Upload Release Asset for Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin\Release\net8.0\publish\windows\Ingestify.exe
          asset_name: Ingestify.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset for MacOS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/Release/net8.0/publish/mac/Ingestify
          asset_name: Ingestify-macos
          asset_content_type: application/octet-stream
