name: .NET Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [win-x64, win-x86, win-arm64, linux-x64, linux-x86, linux-arm, linux-arm64, osx-arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: >
          dotnet publish
          -c Release
          -r ${{ matrix.platform }}
          --self-contained
          -f net8.0
          -o bin\Release\${{ matrix.platform }}\publish\
          /p:PublishSingleFile=false
          /p:PublishReadyToRun=true
          /p:PublishAot=true

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-${{ matrix.platform }}
          path: bin\Release\${{ matrix.platform }}\publish\*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: List files in the publish directory
        run: dir bin\Release\${{ matrix.platform }}\publish

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin\Release\${{ matrix.platform }}\publish\*
          asset_name: ${{ matrix.platform }}-Ingestify
          asset_content_type: application/octet-stream
