name: .NET Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: >
          dotnet publish
          -c Release
          -r win-x64
          --self-contained
          -f net8.0
          -o bin\Release\net8.0\publish\
          /p:PublishSingleFile=false
          /p:PublishReadyToRun=true
          /p:PublishAot=true

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: bin\Release\net8.0\publish\*.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          tag_name:     ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft:        false
          prerelease:   false

      - name: List files in the publish directory
        run: dir bin\Release\net8.0\publish

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin\Release\net8.0\publish\Ingestify.exe
          asset_name: Ingestify.exe
          asset_content_type: application/octet-stream
